export H2 from "./base/h2"
export H3 from "./base/h3"

export Layout from "./layout"
export SEO from "./layout/seo"
export Card from "./common/card"
export Button from "./common/button"
export Section from "./common/section"

export APIsAndMicroservices from "./images/certificates/apis-and-microservices"
export FrontEndLibraries from "./images/certificates/front-end-libraries"
export JavaBasic from "./images/certificates/java-basic"
export JavaScriptAlgorithmsAndDataSturctures from "./images/certificates/javascript-algorithms-and-data-structures"
export JavaScriptBasic from "./images/certificates/javascript-basic"
export ReactBasic from "./images/certificates/react-basic"
export ResponsiveWebDesign from "./images/certificates/responsive-web-design"
export TokopediaSTARTSummit from "./images/certificates/tokopedia-start-summit"
export TypingSpeed from "./images/certificates/typing-speed"

export Certificates from "./pages/index/certificates"
export PinnedGithubProjects from "./pages/index/pinned-github-projects"
export SectionHeader from "./pages/index/section-header"
export TechnicalSkillsOverview from "./pages/index/technical-skills-overview"
